# Generated by Django 5.2.8 on 2025-12-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('employer', 'Employer'), ('job_seeker', 'Job Seeker'), ('admin', 'Admin')], max_length=20),
        ),
    ]
