# Generated by Django 5.2.8 on 2026-01-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('total_clinics', models.IntegerField(default=0)),
                ('total_employers', models.IntegerField(default=0)),
                ('total_job_seekers', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Statistics',
            },
        ),
    ]
